version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo "Installing Node.js..."
      - echo "Installing project dependencies..."
      - npm install
  build:
    commands:
      - echo "Build started on `date`"
      - echo "Building the application..."
      - npm run build
      - echo "Inserting breakpoint for debugging..."
      - codebuild-breakpoint
  post_build:
    commands:
      - echo "Build completed on `date`"
artifacts:
  files:
    - '**/*'
  base-directory: build
